### ISSUE TITLE
status 값이 없는 스트리머 대응

### ISSUE THREAD

**Issue by 321098123** [sw2719/multi-chzzk-recorder#2]
https://chzzk.naver.com/08ce1833b2d0eb463bb7dd0b1e104d79
https://chzzk.naver.com/95f457087270a0bb814bfd1d1fc9d39d

위 두 채널같이 방송을 키지만 api에 status 값이 아예 안적혀 있는 스트리머가 종종 있습니다
방송을 키면 status가 OPEN으로 잡히지만 방송 중이 아닐 때에는 status 값이 없어서 대기할 때 이런 오류가 뜹니다.

`Traceback (most recent call last):
  File "/home/pi/multi_recorder/multi_chzzk_recorder.py", line 743, in <module>
    main()
  File "/home/pi/multi_recorder/multi_chzzk_recorder.py", line 739, in main
    recorder.loop()
  File "/home/pi/multi_recorder/multi_chzzk_recorder.py", line 588, in loop
    is_streaming, stream_data = self.chzzk.check_live(channel_id)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/multi_recorder/api/chzzk.py", line 75, in check_live
    return data['content']['status'] == 'OPEN', data['content']
           ~~~~~~~~~~~~~~~^^^^^^^^^^`

혹시 이런 경우 대비를 위해 스크립트 수정이 가능할까요?

**Comment by sw2719** [comment]
제보 감사합니다. 수정했으니 최신 커밋 pull후 확인해주세요.
